#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ControlHorarios")]
	public partial class BDHorariosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHoras_Trabajada(Horas_Trabajada instance);
    partial void UpdateHoras_Trabajada(Horas_Trabajada instance);
    partial void DeleteHoras_Trabajada(Horas_Trabajada instance);
    partial void InsertObras_Sociale(Obras_Sociale instance);
    partial void UpdateObras_Sociale(Obras_Sociale instance);
    partial void DeleteObras_Sociale(Obras_Sociale instance);
    partial void InsertPaciente(Paciente instance);
    partial void UpdatePaciente(Paciente instance);
    partial void DeletePaciente(Paciente instance);
    partial void InsertTipos_Hora(Tipos_Hora instance);
    partial void UpdateTipos_Hora(Tipos_Hora instance);
    partial void DeleteTipos_Hora(Tipos_Hora instance);
    partial void InsertProfesione(Profesione instance);
    partial void UpdateProfesione(Profesione instance);
    partial void DeleteProfesione(Profesione instance);
    partial void InsertTerapeuta(Terapeuta instance);
    partial void UpdateTerapeuta(Terapeuta instance);
    partial void DeleteTerapeuta(Terapeuta instance);
    #endregion
		
		public BDHorariosDataContext() : 
				base(global::DataBase.Properties.Settings.Default.ControlHorariosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDHorariosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDHorariosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDHorariosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDHorariosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Horas_Trabajada> Horas_Trabajadas
		{
			get
			{
				return this.GetTable<Horas_Trabajada>();
			}
		}
		
		public System.Data.Linq.Table<Obras_Sociale> Obras_Sociales
		{
			get
			{
				return this.GetTable<Obras_Sociale>();
			}
		}
		
		public System.Data.Linq.Table<Paciente> Pacientes
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<Tipos_Hora> Tipos_Horas
		{
			get
			{
				return this.GetTable<Tipos_Hora>();
			}
		}
		
		public System.Data.Linq.Table<Profesione> Profesiones
		{
			get
			{
				return this.GetTable<Profesione>();
			}
		}
		
		public System.Data.Linq.Table<Terapeuta> Terapeutas
		{
			get
			{
				return this.GetTable<Terapeuta>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarHorasTrabajadas")]
		public ISingleResult<ListarHorasTrabajadasResult> ListarHorasTrabajadas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="VarChar(20)")] string mes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mes);
			return ((ISingleResult<ListarHorasTrabajadasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarHorasTrabajadasPagas")]
		public ISingleResult<ListarHorasTrabajadasPagasResult> ListarHorasTrabajadasPagas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="VarChar(20)")] string mes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mes);
			return ((ISingleResult<ListarHorasTrabajadasPagasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarObrasSociales")]
		public ISingleResult<ListarObrasSocialesResult> ListarObrasSociales()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarObrasSocialesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarPacientes")]
		public ISingleResult<ListarPacientesResult> ListarPacientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarPacientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarProfesiones")]
		public ISingleResult<ListarProfesionesResult> ListarProfesiones()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarProfesionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarTerapeutas")]
		public ISingleResult<ListarTerapeutasResult> ListarTerapeutas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarTerapeutasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarTiposHoras")]
		public ISingleResult<ListarTiposHorasResult> ListarTiposHoras()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarTiposHorasResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horas_Trabajadas")]
	public partial class Horas_Trabajada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HrTrab_Id;
		
		private decimal _HrTrab_Cant;
		
		private string _HrTrab_Mes;
		
		private string _HrTrab_Lugar;
		
		private decimal _HrTrab_Precio;
		
		private int _HrTrab_Ter;
		
		private int _HrTrab_Pac;
		
		private int _HrTrab_TipoHr;
		
		private bool _HrTrab_Cob;
		
		private EntityRef<Paciente> _Paciente;
		
		private EntityRef<Tipos_Hora> _Tipos_Hora;
		
		private EntityRef<Terapeuta> _Terapeuta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHrTrab_IdChanging(int value);
    partial void OnHrTrab_IdChanged();
    partial void OnHrTrab_CantChanging(decimal value);
    partial void OnHrTrab_CantChanged();
    partial void OnHrTrab_MesChanging(string value);
    partial void OnHrTrab_MesChanged();
    partial void OnHrTrab_LugarChanging(string value);
    partial void OnHrTrab_LugarChanged();
    partial void OnHrTrab_PrecioChanging(decimal value);
    partial void OnHrTrab_PrecioChanged();
    partial void OnHrTrab_TerChanging(int value);
    partial void OnHrTrab_TerChanged();
    partial void OnHrTrab_PacChanging(int value);
    partial void OnHrTrab_PacChanged();
    partial void OnHrTrab_TipoHrChanging(int value);
    partial void OnHrTrab_TipoHrChanged();
    partial void OnHrTrab_CobChanging(bool value);
    partial void OnHrTrab_CobChanged();
    #endregion
		
		public Horas_Trabajada()
		{
			this._Paciente = default(EntityRef<Paciente>);
			this._Tipos_Hora = default(EntityRef<Tipos_Hora>);
			this._Terapeuta = default(EntityRef<Terapeuta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HrTrab_Id
		{
			get
			{
				return this._HrTrab_Id;
			}
			set
			{
				if ((this._HrTrab_Id != value))
				{
					this.OnHrTrab_IdChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Id = value;
					this.SendPropertyChanged("HrTrab_Id");
					this.OnHrTrab_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Cant", DbType="Decimal(10,2) NOT NULL")]
		public decimal HrTrab_Cant
		{
			get
			{
				return this._HrTrab_Cant;
			}
			set
			{
				if ((this._HrTrab_Cant != value))
				{
					this.OnHrTrab_CantChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Cant = value;
					this.SendPropertyChanged("HrTrab_Cant");
					this.OnHrTrab_CantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Mes", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string HrTrab_Mes
		{
			get
			{
				return this._HrTrab_Mes;
			}
			set
			{
				if ((this._HrTrab_Mes != value))
				{
					this.OnHrTrab_MesChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Mes = value;
					this.SendPropertyChanged("HrTrab_Mes");
					this.OnHrTrab_MesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Lugar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HrTrab_Lugar
		{
			get
			{
				return this._HrTrab_Lugar;
			}
			set
			{
				if ((this._HrTrab_Lugar != value))
				{
					this.OnHrTrab_LugarChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Lugar = value;
					this.SendPropertyChanged("HrTrab_Lugar");
					this.OnHrTrab_LugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal HrTrab_Precio
		{
			get
			{
				return this._HrTrab_Precio;
			}
			set
			{
				if ((this._HrTrab_Precio != value))
				{
					this.OnHrTrab_PrecioChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Precio = value;
					this.SendPropertyChanged("HrTrab_Precio");
					this.OnHrTrab_PrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Ter", DbType="Int NOT NULL")]
		public int HrTrab_Ter
		{
			get
			{
				return this._HrTrab_Ter;
			}
			set
			{
				if ((this._HrTrab_Ter != value))
				{
					if (this._Terapeuta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHrTrab_TerChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Ter = value;
					this.SendPropertyChanged("HrTrab_Ter");
					this.OnHrTrab_TerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Pac", DbType="Int NOT NULL")]
		public int HrTrab_Pac
		{
			get
			{
				return this._HrTrab_Pac;
			}
			set
			{
				if ((this._HrTrab_Pac != value))
				{
					if (this._Paciente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHrTrab_PacChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Pac = value;
					this.SendPropertyChanged("HrTrab_Pac");
					this.OnHrTrab_PacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_TipoHr", DbType="Int NOT NULL")]
		public int HrTrab_TipoHr
		{
			get
			{
				return this._HrTrab_TipoHr;
			}
			set
			{
				if ((this._HrTrab_TipoHr != value))
				{
					if (this._Tipos_Hora.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHrTrab_TipoHrChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_TipoHr = value;
					this.SendPropertyChanged("HrTrab_TipoHr");
					this.OnHrTrab_TipoHrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HrTrab_Cob", DbType="Bit NOT NULL")]
		public bool HrTrab_Cob
		{
			get
			{
				return this._HrTrab_Cob;
			}
			set
			{
				if ((this._HrTrab_Cob != value))
				{
					this.OnHrTrab_CobChanging(value);
					this.SendPropertyChanging();
					this._HrTrab_Cob = value;
					this.SendPropertyChanged("HrTrab_Cob");
					this.OnHrTrab_CobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Horas_Trabajada", Storage="_Paciente", ThisKey="HrTrab_Pac", OtherKey="Paciente_Id", IsForeignKey=true)]
		public Paciente Paciente
		{
			get
			{
				return this._Paciente.Entity;
			}
			set
			{
				Paciente previousValue = this._Paciente.Entity;
				if (((previousValue != value) 
							|| (this._Paciente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paciente.Entity = null;
						previousValue.Horas_Trabajadas.Remove(this);
					}
					this._Paciente.Entity = value;
					if ((value != null))
					{
						value.Horas_Trabajadas.Add(this);
						this._HrTrab_Pac = value.Paciente_Id;
					}
					else
					{
						this._HrTrab_Pac = default(int);
					}
					this.SendPropertyChanged("Paciente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipos_Hora_Horas_Trabajada", Storage="_Tipos_Hora", ThisKey="HrTrab_TipoHr", OtherKey="TipoHora_Id", IsForeignKey=true)]
		public Tipos_Hora Tipos_Hora
		{
			get
			{
				return this._Tipos_Hora.Entity;
			}
			set
			{
				Tipos_Hora previousValue = this._Tipos_Hora.Entity;
				if (((previousValue != value) 
							|| (this._Tipos_Hora.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipos_Hora.Entity = null;
						previousValue.Horas_Trabajadas.Remove(this);
					}
					this._Tipos_Hora.Entity = value;
					if ((value != null))
					{
						value.Horas_Trabajadas.Add(this);
						this._HrTrab_TipoHr = value.TipoHora_Id;
					}
					else
					{
						this._HrTrab_TipoHr = default(int);
					}
					this.SendPropertyChanged("Tipos_Hora");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Terapeuta_Horas_Trabajada", Storage="_Terapeuta", ThisKey="HrTrab_Ter", OtherKey="Terapeuta_Id", IsForeignKey=true)]
		public Terapeuta Terapeuta
		{
			get
			{
				return this._Terapeuta.Entity;
			}
			set
			{
				Terapeuta previousValue = this._Terapeuta.Entity;
				if (((previousValue != value) 
							|| (this._Terapeuta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Terapeuta.Entity = null;
						previousValue.Horas_Trabajadas.Remove(this);
					}
					this._Terapeuta.Entity = value;
					if ((value != null))
					{
						value.Horas_Trabajadas.Add(this);
						this._HrTrab_Ter = value.Terapeuta_Id;
					}
					else
					{
						this._HrTrab_Ter = default(int);
					}
					this.SendPropertyChanged("Terapeuta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Obras_Sociales")]
	public partial class Obras_Sociale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ObSoc_Id;
		
		private string _ObSoc_Nom;
		
		private EntitySet<Paciente> _Pacientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObSoc_IdChanging(int value);
    partial void OnObSoc_IdChanged();
    partial void OnObSoc_NomChanging(string value);
    partial void OnObSoc_NomChanged();
    #endregion
		
		public Obras_Sociale()
		{
			this._Pacientes = new EntitySet<Paciente>(new Action<Paciente>(this.attach_Pacientes), new Action<Paciente>(this.detach_Pacientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObSoc_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ObSoc_Id
		{
			get
			{
				return this._ObSoc_Id;
			}
			set
			{
				if ((this._ObSoc_Id != value))
				{
					this.OnObSoc_IdChanging(value);
					this.SendPropertyChanging();
					this._ObSoc_Id = value;
					this.SendPropertyChanged("ObSoc_Id");
					this.OnObSoc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObSoc_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ObSoc_Nom
		{
			get
			{
				return this._ObSoc_Nom;
			}
			set
			{
				if ((this._ObSoc_Nom != value))
				{
					this.OnObSoc_NomChanging(value);
					this.SendPropertyChanging();
					this._ObSoc_Nom = value;
					this.SendPropertyChanged("ObSoc_Nom");
					this.OnObSoc_NomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Obras_Sociale_Paciente", Storage="_Pacientes", ThisKey="ObSoc_Id", OtherKey="Paciente_OS")]
		public EntitySet<Paciente> Pacientes
		{
			get
			{
				return this._Pacientes;
			}
			set
			{
				this._Pacientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pacientes(Paciente entity)
		{
			this.SendPropertyChanging();
			entity.Obras_Sociale = this;
		}
		
		private void detach_Pacientes(Paciente entity)
		{
			this.SendPropertyChanging();
			entity.Obras_Sociale = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pacientes")]
	public partial class Paciente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Paciente_Id;
		
		private string _Paciente_Nom;
		
		private string _Paciente_Ape;
		
		private string _Paciente_Doc;
		
		private string _Paciente_FecNac;
		
		private string _Paciente_Dom;
		
		private string _Paciente_Tel;
		
		private int _Paciente_OS;
		
		private EntitySet<Horas_Trabajada> _Horas_Trabajadas;
		
		private EntityRef<Obras_Sociale> _Obras_Sociale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaciente_IdChanging(int value);
    partial void OnPaciente_IdChanged();
    partial void OnPaciente_NomChanging(string value);
    partial void OnPaciente_NomChanged();
    partial void OnPaciente_ApeChanging(string value);
    partial void OnPaciente_ApeChanged();
    partial void OnPaciente_DocChanging(string value);
    partial void OnPaciente_DocChanged();
    partial void OnPaciente_FecNacChanging(string value);
    partial void OnPaciente_FecNacChanged();
    partial void OnPaciente_DomChanging(string value);
    partial void OnPaciente_DomChanged();
    partial void OnPaciente_TelChanging(string value);
    partial void OnPaciente_TelChanged();
    partial void OnPaciente_OSChanging(int value);
    partial void OnPaciente_OSChanged();
    #endregion
		
		public Paciente()
		{
			this._Horas_Trabajadas = new EntitySet<Horas_Trabajada>(new Action<Horas_Trabajada>(this.attach_Horas_Trabajadas), new Action<Horas_Trabajada>(this.detach_Horas_Trabajadas));
			this._Obras_Sociale = default(EntityRef<Obras_Sociale>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Paciente_Id
		{
			get
			{
				return this._Paciente_Id;
			}
			set
			{
				if ((this._Paciente_Id != value))
				{
					this.OnPaciente_IdChanging(value);
					this.SendPropertyChanging();
					this._Paciente_Id = value;
					this.SendPropertyChanged("Paciente_Id");
					this.OnPaciente_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Paciente_Nom
		{
			get
			{
				return this._Paciente_Nom;
			}
			set
			{
				if ((this._Paciente_Nom != value))
				{
					this.OnPaciente_NomChanging(value);
					this.SendPropertyChanging();
					this._Paciente_Nom = value;
					this.SendPropertyChanged("Paciente_Nom");
					this.OnPaciente_NomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_Ape", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Paciente_Ape
		{
			get
			{
				return this._Paciente_Ape;
			}
			set
			{
				if ((this._Paciente_Ape != value))
				{
					this.OnPaciente_ApeChanging(value);
					this.SendPropertyChanging();
					this._Paciente_Ape = value;
					this.SendPropertyChanged("Paciente_Ape");
					this.OnPaciente_ApeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_Doc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Paciente_Doc
		{
			get
			{
				return this._Paciente_Doc;
			}
			set
			{
				if ((this._Paciente_Doc != value))
				{
					this.OnPaciente_DocChanging(value);
					this.SendPropertyChanging();
					this._Paciente_Doc = value;
					this.SendPropertyChanged("Paciente_Doc");
					this.OnPaciente_DocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_FecNac", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Paciente_FecNac
		{
			get
			{
				return this._Paciente_FecNac;
			}
			set
			{
				if ((this._Paciente_FecNac != value))
				{
					this.OnPaciente_FecNacChanging(value);
					this.SendPropertyChanging();
					this._Paciente_FecNac = value;
					this.SendPropertyChanged("Paciente_FecNac");
					this.OnPaciente_FecNacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_Dom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Paciente_Dom
		{
			get
			{
				return this._Paciente_Dom;
			}
			set
			{
				if ((this._Paciente_Dom != value))
				{
					this.OnPaciente_DomChanging(value);
					this.SendPropertyChanging();
					this._Paciente_Dom = value;
					this.SendPropertyChanged("Paciente_Dom");
					this.OnPaciente_DomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_Tel", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Paciente_Tel
		{
			get
			{
				return this._Paciente_Tel;
			}
			set
			{
				if ((this._Paciente_Tel != value))
				{
					this.OnPaciente_TelChanging(value);
					this.SendPropertyChanging();
					this._Paciente_Tel = value;
					this.SendPropertyChanged("Paciente_Tel");
					this.OnPaciente_TelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente_OS", DbType="Int NOT NULL")]
		public int Paciente_OS
		{
			get
			{
				return this._Paciente_OS;
			}
			set
			{
				if ((this._Paciente_OS != value))
				{
					if (this._Obras_Sociale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPaciente_OSChanging(value);
					this.SendPropertyChanging();
					this._Paciente_OS = value;
					this.SendPropertyChanged("Paciente_OS");
					this.OnPaciente_OSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paciente_Horas_Trabajada", Storage="_Horas_Trabajadas", ThisKey="Paciente_Id", OtherKey="HrTrab_Pac")]
		public EntitySet<Horas_Trabajada> Horas_Trabajadas
		{
			get
			{
				return this._Horas_Trabajadas;
			}
			set
			{
				this._Horas_Trabajadas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Obras_Sociale_Paciente", Storage="_Obras_Sociale", ThisKey="Paciente_OS", OtherKey="ObSoc_Id", IsForeignKey=true)]
		public Obras_Sociale Obras_Sociale
		{
			get
			{
				return this._Obras_Sociale.Entity;
			}
			set
			{
				Obras_Sociale previousValue = this._Obras_Sociale.Entity;
				if (((previousValue != value) 
							|| (this._Obras_Sociale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Obras_Sociale.Entity = null;
						previousValue.Pacientes.Remove(this);
					}
					this._Obras_Sociale.Entity = value;
					if ((value != null))
					{
						value.Pacientes.Add(this);
						this._Paciente_OS = value.ObSoc_Id;
					}
					else
					{
						this._Paciente_OS = default(int);
					}
					this.SendPropertyChanged("Obras_Sociale");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Horas_Trabajadas(Horas_Trabajada entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = this;
		}
		
		private void detach_Horas_Trabajadas(Horas_Trabajada entity)
		{
			this.SendPropertyChanging();
			entity.Paciente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipos_Horas")]
	public partial class Tipos_Hora : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TipoHora_Id;
		
		private string _TipoHora_Nom;
		
		private decimal _TipoHora_Precio;
		
		private EntitySet<Horas_Trabajada> _Horas_Trabajadas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoHora_IdChanging(int value);
    partial void OnTipoHora_IdChanged();
    partial void OnTipoHora_NomChanging(string value);
    partial void OnTipoHora_NomChanged();
    partial void OnTipoHora_PrecioChanging(decimal value);
    partial void OnTipoHora_PrecioChanged();
    #endregion
		
		public Tipos_Hora()
		{
			this._Horas_Trabajadas = new EntitySet<Horas_Trabajada>(new Action<Horas_Trabajada>(this.attach_Horas_Trabajadas), new Action<Horas_Trabajada>(this.detach_Horas_Trabajadas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoHora_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TipoHora_Id
		{
			get
			{
				return this._TipoHora_Id;
			}
			set
			{
				if ((this._TipoHora_Id != value))
				{
					this.OnTipoHora_IdChanging(value);
					this.SendPropertyChanging();
					this._TipoHora_Id = value;
					this.SendPropertyChanged("TipoHora_Id");
					this.OnTipoHora_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoHora_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoHora_Nom
		{
			get
			{
				return this._TipoHora_Nom;
			}
			set
			{
				if ((this._TipoHora_Nom != value))
				{
					this.OnTipoHora_NomChanging(value);
					this.SendPropertyChanging();
					this._TipoHora_Nom = value;
					this.SendPropertyChanged("TipoHora_Nom");
					this.OnTipoHora_NomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoHora_Precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal TipoHora_Precio
		{
			get
			{
				return this._TipoHora_Precio;
			}
			set
			{
				if ((this._TipoHora_Precio != value))
				{
					this.OnTipoHora_PrecioChanging(value);
					this.SendPropertyChanging();
					this._TipoHora_Precio = value;
					this.SendPropertyChanged("TipoHora_Precio");
					this.OnTipoHora_PrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipos_Hora_Horas_Trabajada", Storage="_Horas_Trabajadas", ThisKey="TipoHora_Id", OtherKey="HrTrab_TipoHr")]
		public EntitySet<Horas_Trabajada> Horas_Trabajadas
		{
			get
			{
				return this._Horas_Trabajadas;
			}
			set
			{
				this._Horas_Trabajadas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Horas_Trabajadas(Horas_Trabajada entity)
		{
			this.SendPropertyChanging();
			entity.Tipos_Hora = this;
		}
		
		private void detach_Horas_Trabajadas(Horas_Trabajada entity)
		{
			this.SendPropertyChanging();
			entity.Tipos_Hora = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesiones")]
	public partial class Profesione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Profesion_Id;
		
		private string _Profesion_Nom;
		
		private EntitySet<Terapeuta> _Terapeutas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProfesion_IdChanging(int value);
    partial void OnProfesion_IdChanged();
    partial void OnProfesion_NomChanging(string value);
    partial void OnProfesion_NomChanged();
    #endregion
		
		public Profesione()
		{
			this._Terapeutas = new EntitySet<Terapeuta>(new Action<Terapeuta>(this.attach_Terapeutas), new Action<Terapeuta>(this.detach_Terapeutas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Profesion_Id
		{
			get
			{
				return this._Profesion_Id;
			}
			set
			{
				if ((this._Profesion_Id != value))
				{
					this.OnProfesion_IdChanging(value);
					this.SendPropertyChanging();
					this._Profesion_Id = value;
					this.SendPropertyChanged("Profesion_Id");
					this.OnProfesion_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Profesion_Nom
		{
			get
			{
				return this._Profesion_Nom;
			}
			set
			{
				if ((this._Profesion_Nom != value))
				{
					this.OnProfesion_NomChanging(value);
					this.SendPropertyChanging();
					this._Profesion_Nom = value;
					this.SendPropertyChanged("Profesion_Nom");
					this.OnProfesion_NomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesione_Terapeuta", Storage="_Terapeutas", ThisKey="Profesion_Id", OtherKey="Terapeuta_Prof")]
		public EntitySet<Terapeuta> Terapeutas
		{
			get
			{
				return this._Terapeutas;
			}
			set
			{
				this._Terapeutas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Terapeutas(Terapeuta entity)
		{
			this.SendPropertyChanging();
			entity.Profesione = this;
		}
		
		private void detach_Terapeutas(Terapeuta entity)
		{
			this.SendPropertyChanging();
			entity.Profesione = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Terapeutas")]
	public partial class Terapeuta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Terapeuta_Id;
		
		private string _Terapeuta_Nom;
		
		private string _Terapeuta_Ape;
		
		private string _Terapeuta_Mat;
		
		private string _Terapeuta_Doc;
		
		private string _Terapeuta_Mail;
		
		private string _Terapeuta_Dom;
		
		private string _Terapeuta_Tel;
		
		private int _Terapeuta_Prof;
		
		private EntitySet<Horas_Trabajada> _Horas_Trabajadas;
		
		private EntityRef<Profesione> _Profesione;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTerapeuta_IdChanging(int value);
    partial void OnTerapeuta_IdChanged();
    partial void OnTerapeuta_NomChanging(string value);
    partial void OnTerapeuta_NomChanged();
    partial void OnTerapeuta_ApeChanging(string value);
    partial void OnTerapeuta_ApeChanged();
    partial void OnTerapeuta_MatChanging(string value);
    partial void OnTerapeuta_MatChanged();
    partial void OnTerapeuta_DocChanging(string value);
    partial void OnTerapeuta_DocChanged();
    partial void OnTerapeuta_MailChanging(string value);
    partial void OnTerapeuta_MailChanged();
    partial void OnTerapeuta_DomChanging(string value);
    partial void OnTerapeuta_DomChanged();
    partial void OnTerapeuta_TelChanging(string value);
    partial void OnTerapeuta_TelChanged();
    partial void OnTerapeuta_ProfChanging(int value);
    partial void OnTerapeuta_ProfChanged();
    #endregion
		
		public Terapeuta()
		{
			this._Horas_Trabajadas = new EntitySet<Horas_Trabajada>(new Action<Horas_Trabajada>(this.attach_Horas_Trabajadas), new Action<Horas_Trabajada>(this.detach_Horas_Trabajadas));
			this._Profesione = default(EntityRef<Profesione>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Terapeuta_Id
		{
			get
			{
				return this._Terapeuta_Id;
			}
			set
			{
				if ((this._Terapeuta_Id != value))
				{
					this.OnTerapeuta_IdChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Id = value;
					this.SendPropertyChanged("Terapeuta_Id");
					this.OnTerapeuta_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Nom
		{
			get
			{
				return this._Terapeuta_Nom;
			}
			set
			{
				if ((this._Terapeuta_Nom != value))
				{
					this.OnTerapeuta_NomChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Nom = value;
					this.SendPropertyChanged("Terapeuta_Nom");
					this.OnTerapeuta_NomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Ape", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Ape
		{
			get
			{
				return this._Terapeuta_Ape;
			}
			set
			{
				if ((this._Terapeuta_Ape != value))
				{
					this.OnTerapeuta_ApeChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Ape = value;
					this.SendPropertyChanged("Terapeuta_Ape");
					this.OnTerapeuta_ApeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Mat", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Mat
		{
			get
			{
				return this._Terapeuta_Mat;
			}
			set
			{
				if ((this._Terapeuta_Mat != value))
				{
					this.OnTerapeuta_MatChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Mat = value;
					this.SendPropertyChanged("Terapeuta_Mat");
					this.OnTerapeuta_MatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Doc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Doc
		{
			get
			{
				return this._Terapeuta_Doc;
			}
			set
			{
				if ((this._Terapeuta_Doc != value))
				{
					this.OnTerapeuta_DocChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Doc = value;
					this.SendPropertyChanged("Terapeuta_Doc");
					this.OnTerapeuta_DocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Mail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Mail
		{
			get
			{
				return this._Terapeuta_Mail;
			}
			set
			{
				if ((this._Terapeuta_Mail != value))
				{
					this.OnTerapeuta_MailChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Mail = value;
					this.SendPropertyChanged("Terapeuta_Mail");
					this.OnTerapeuta_MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Dom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Dom
		{
			get
			{
				return this._Terapeuta_Dom;
			}
			set
			{
				if ((this._Terapeuta_Dom != value))
				{
					this.OnTerapeuta_DomChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Dom = value;
					this.SendPropertyChanged("Terapeuta_Dom");
					this.OnTerapeuta_DomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Tel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Terapeuta_Tel
		{
			get
			{
				return this._Terapeuta_Tel;
			}
			set
			{
				if ((this._Terapeuta_Tel != value))
				{
					this.OnTerapeuta_TelChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Tel = value;
					this.SendPropertyChanged("Terapeuta_Tel");
					this.OnTerapeuta_TelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Terapeuta_Prof", DbType="Int NOT NULL")]
		public int Terapeuta_Prof
		{
			get
			{
				return this._Terapeuta_Prof;
			}
			set
			{
				if ((this._Terapeuta_Prof != value))
				{
					if (this._Profesione.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTerapeuta_ProfChanging(value);
					this.SendPropertyChanging();
					this._Terapeuta_Prof = value;
					this.SendPropertyChanged("Terapeuta_Prof");
					this.OnTerapeuta_ProfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Terapeuta_Horas_Trabajada", Storage="_Horas_Trabajadas", ThisKey="Terapeuta_Id", OtherKey="HrTrab_Ter")]
		public EntitySet<Horas_Trabajada> Horas_Trabajadas
		{
			get
			{
				return this._Horas_Trabajadas;
			}
			set
			{
				this._Horas_Trabajadas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesione_Terapeuta", Storage="_Profesione", ThisKey="Terapeuta_Prof", OtherKey="Profesion_Id", IsForeignKey=true)]
		public Profesione Profesione
		{
			get
			{
				return this._Profesione.Entity;
			}
			set
			{
				Profesione previousValue = this._Profesione.Entity;
				if (((previousValue != value) 
							|| (this._Profesione.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesione.Entity = null;
						previousValue.Terapeutas.Remove(this);
					}
					this._Profesione.Entity = value;
					if ((value != null))
					{
						value.Terapeutas.Add(this);
						this._Terapeuta_Prof = value.Profesion_Id;
					}
					else
					{
						this._Terapeuta_Prof = default(int);
					}
					this.SendPropertyChanged("Profesione");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Horas_Trabajadas(Horas_Trabajada entity)
		{
			this.SendPropertyChanging();
			entity.Terapeuta = this;
		}
		
		private void detach_Horas_Trabajadas(Horas_Trabajada entity)
		{
			this.SendPropertyChanging();
			entity.Terapeuta = null;
		}
	}
	
	public partial class ListarHorasTrabajadasResult
	{
		
		private int _Id;
		
		private string _ApellidoTerapeuta;
		
		private string _NombreTerapeuta;
		
		private string _PacienteApellido;
		
		private string _NombrePaciente;
		
		private string _TipoHora;
		
		private decimal _Total;
		
		private string _Lugar;
		
		private string _Mes;
		
		private decimal _Horas;
		
		private bool _Cobrada;
		
		public ListarHorasTrabajadasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoTerapeuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoTerapeuta
		{
			get
			{
				return this._ApellidoTerapeuta;
			}
			set
			{
				if ((this._ApellidoTerapeuta != value))
				{
					this._ApellidoTerapeuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreTerapeuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreTerapeuta
		{
			get
			{
				return this._NombreTerapeuta;
			}
			set
			{
				if ((this._NombreTerapeuta != value))
				{
					this._NombreTerapeuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PacienteApellido
		{
			get
			{
				return this._PacienteApellido;
			}
			set
			{
				if ((this._PacienteApellido != value))
				{
					this._PacienteApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePaciente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombrePaciente
		{
			get
			{
				return this._NombrePaciente;
			}
			set
			{
				if ((this._NombrePaciente != value))
				{
					this._NombrePaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoHora", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoHora
		{
			get
			{
				return this._TipoHora;
			}
			set
			{
				if ((this._TipoHora != value))
				{
					this._TipoHora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(10,2) NOT NULL")]
		public decimal Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this._Lugar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mes", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this._Mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas", DbType="Decimal(10,2) NOT NULL")]
		public decimal Horas
		{
			get
			{
				return this._Horas;
			}
			set
			{
				if ((this._Horas != value))
				{
					this._Horas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cobrada", DbType="Bit NOT NULL")]
		public bool Cobrada
		{
			get
			{
				return this._Cobrada;
			}
			set
			{
				if ((this._Cobrada != value))
				{
					this._Cobrada = value;
				}
			}
		}
	}
	
	public partial class ListarHorasTrabajadasPagasResult
	{
		
		private int _Id;
		
		private string _ApellidoTerapeuta;
		
		private string _NombreTerapeuta;
		
		private string _PacienteApellido;
		
		private string _NombrePaciente;
		
		private string _TipoHora;
		
		private decimal _Total;
		
		private string _Lugar;
		
		private string _Mes;
		
		private decimal _Horas;
		
		private bool _Cobrada;
		
		public ListarHorasTrabajadasPagasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoTerapeuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApellidoTerapeuta
		{
			get
			{
				return this._ApellidoTerapeuta;
			}
			set
			{
				if ((this._ApellidoTerapeuta != value))
				{
					this._ApellidoTerapeuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreTerapeuta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreTerapeuta
		{
			get
			{
				return this._NombreTerapeuta;
			}
			set
			{
				if ((this._NombreTerapeuta != value))
				{
					this._NombreTerapeuta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacienteApellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PacienteApellido
		{
			get
			{
				return this._PacienteApellido;
			}
			set
			{
				if ((this._PacienteApellido != value))
				{
					this._PacienteApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePaciente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombrePaciente
		{
			get
			{
				return this._NombrePaciente;
			}
			set
			{
				if ((this._NombrePaciente != value))
				{
					this._NombrePaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoHora", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoHora
		{
			get
			{
				return this._TipoHora;
			}
			set
			{
				if ((this._TipoHora != value))
				{
					this._TipoHora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(10,2) NOT NULL")]
		public decimal Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this._Lugar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mes", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this._Mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas", DbType="Decimal(10,2) NOT NULL")]
		public decimal Horas
		{
			get
			{
				return this._Horas;
			}
			set
			{
				if ((this._Horas != value))
				{
					this._Horas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cobrada", DbType="Bit NOT NULL")]
		public bool Cobrada
		{
			get
			{
				return this._Cobrada;
			}
			set
			{
				if ((this._Cobrada != value))
				{
					this._Cobrada = value;
				}
			}
		}
	}
	
	public partial class ListarObrasSocialesResult
	{
		
		private int _Id;
		
		private string _Nombre;
		
		public ListarObrasSocialesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class ListarPacientesResult
	{
		
		private int _ID;
		
		private string _Apellido;
		
		private string _Nombre;
		
		private string _Documento;
		
		private string _Fecha_Nac;
		
		private string _Domicilio;
		
		private string _Telefono;
		
		private string _Obra_Social;
		
		public ListarPacientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this._Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Nac]", Storage="_Fecha_Nac", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this._Fecha_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this._Domicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Obra Social]", Storage="_Obra_Social", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Obra_Social
		{
			get
			{
				return this._Obra_Social;
			}
			set
			{
				if ((this._Obra_Social != value))
				{
					this._Obra_Social = value;
				}
			}
		}
	}
	
	public partial class ListarProfesionesResult
	{
		
		private int _Id;
		
		private string _Nombre;
		
		public ListarProfesionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class ListarTerapeutasResult
	{
		
		private int _ID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _Documento;
		
		private string _Matricula;
		
		private string _Domicilio;
		
		private string _Mail;
		
		private string _Telefono;
		
		private string _Profesion;
		
		public ListarTerapeutasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this._Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					this._Matricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domicilio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Domicilio
		{
			get
			{
				return this._Domicilio;
			}
			set
			{
				if ((this._Domicilio != value))
				{
					this._Domicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this._Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Profesion
		{
			get
			{
				return this._Profesion;
			}
			set
			{
				if ((this._Profesion != value))
				{
					this._Profesion = value;
				}
			}
		}
	}
	
	public partial class ListarTiposHorasResult
	{
		
		private int _Id;
		
		private string _Nombre;
		
		private decimal _Valor;
		
		public ListarTiposHorasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(10,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this._Valor = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
