#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="controlhorariodb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertobrasocial(obrasocial instance);
    partial void Updateobrasocial(obrasocial instance);
    partial void Deleteobrasocial(obrasocial instance);
    partial void Insertprofesion(profesion instance);
    partial void Updateprofesion(profesion instance);
    partial void Deleteprofesion(profesion instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DataBase.Properties.Settings.Default.controlhorariodbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<obrasocial> obrasocials
		{
			get
			{
				return this.GetTable<obrasocial>();
			}
		}
		
		public System.Data.Linq.Table<profesion> profesions
		{
			get
			{
				return this.GetTable<profesion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.obrasocial")]
	public partial class obrasocial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_ObraSocial;
		
		private string _obrasocial_nom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ObraSocialChanging(int value);
    partial void OnId_ObraSocialChanged();
    partial void Onobrasocial_nomChanging(string value);
    partial void Onobrasocial_nomChanged();
    #endregion
		
		public obrasocial()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_ObraSocial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_ObraSocial
		{
			get
			{
				return this._Id_ObraSocial;
			}
			set
			{
				if ((this._Id_ObraSocial != value))
				{
					this.OnId_ObraSocialChanging(value);
					this.SendPropertyChanging();
					this._Id_ObraSocial = value;
					this.SendPropertyChanged("Id_ObraSocial");
					this.OnId_ObraSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obrasocial_nom", DbType="Char(30)")]
		public string obrasocial_nom
		{
			get
			{
				return this._obrasocial_nom;
			}
			set
			{
				if ((this._obrasocial_nom != value))
				{
					this.Onobrasocial_nomChanging(value);
					this.SendPropertyChanging();
					this._obrasocial_nom = value;
					this.SendPropertyChanged("obrasocial_nom");
					this.Onobrasocial_nomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.profesion")]
	public partial class profesion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Profesion;
		
		private string _pofesion_nom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ProfesionChanging(int value);
    partial void OnId_ProfesionChanged();
    partial void Onpofesion_nomChanging(string value);
    partial void Onpofesion_nomChanged();
    #endregion
		
		public profesion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Profesion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Profesion
		{
			get
			{
				return this._Id_Profesion;
			}
			set
			{
				if ((this._Id_Profesion != value))
				{
					this.OnId_ProfesionChanging(value);
					this.SendPropertyChanging();
					this._Id_Profesion = value;
					this.SendPropertyChanged("Id_Profesion");
					this.OnId_ProfesionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pofesion_nom", DbType="Char(30)")]
		public string pofesion_nom
		{
			get
			{
				return this._pofesion_nom;
			}
			set
			{
				if ((this._pofesion_nom != value))
				{
					this.Onpofesion_nomChanging(value);
					this.SendPropertyChanging();
					this._pofesion_nom = value;
					this.SendPropertyChanged("pofesion_nom");
					this.Onpofesion_nomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
